name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        mkdir -p build
        GOARCH=amd64 GOOS=linux go build -o ./build/api-linux-x64 ./cmd/api
        GOARCH=amd64 GOOS=linux go build -o ./build/cli-linux-x64 ./cmd/cli
        GOARCH=amd64 GOOS=darwin go build -o ./build/cli-darwin-x64 ./cmd/cli
        GOARCH=amd64 GOOS=windows go build -o ./build/cli-win-x64.exe ./cmd/cli
        (cd build; zip keymaster-api.zip api-linux-x64)

    - name: Test
      run: go test -v ./...
